QUESTIONS = {
    "Python": {
        "Basics": [
            {"question": "Which keyword is used to define a function?", "options": ["function","def","fn","lambda"], "answer": "def"},
            {"question": "How do you start a comment in Python?", "options": ["//","#","/*","<!--"], "answer": "#"},
            {"question": "What is the type of 'Hello'?", "options": ["str","int","list","dict"], "answer": "str"},
            {"question": "Which operator is exponentiation?", "options": ["^","**","pow()","exp()"], "answer": "**"},
            {"question": "What is the index of first element in list?", "options": ["1","0","-1","None"], "answer": "0"},
            {"question": "Which function prints to console?", "options": ["echo()","print()","puts()","logger()"], "answer": "print()"},
            {"question": "What does len([1,2,3]) return?", "options": ["2","3","4","Error"], "answer": "3"},
            {"question": "Which statement exits a loop immediately?", "options": ["stop","break","exit","continue"], "answer": "break"},
            {"question": "Which method adds item to end of list?", "options": ["append()","add()","push()","insert()"], "answer": "append()"},
            {"question": "Which literal creates bytes?", "options": ["b'abc'","'abc'","u'abc'","r'abc'"], "answer": "b'abc'"},
            {"question": "How to create an empty dictionary?", "options": ["{}","[]","()","set()"], "answer": "{}"},
            {"question": "Which keyword creates anonymous function?", "options": ["anon","lambda","def","func"], "answer": "lambda"},
            {"question": "What does 'is' compare?", "options": ["value","identity","type","length"], "answer": "identity"},
            {"question": "Which converts to integer?", "options": ["int()","to_int()","cast()","integer()"], "answer": "int()"},
            {"question": "Which built-in returns type of variable?", "options": ["type()","typeof()","gettype()","klass()"], "answer": "type()"},
            {"question": "Which is immutable?", "options": ["list","dict","tuple","set"], "answer": "tuple"},
            {"question": "What will 'a' * 3 produce?", "options": ["'aaa'","['a','a','a']","Error","'a3'"], "answer": "'aaa'"},
            {"question": "Which operator is for floor division?", "options": ["/","//","%","div"], "answer": "//"},
            {"question": "Which boolean values exist in Python?", "options": ["true/false","1/0","True/False","yes/no"], "answer": "True/False"},
            {"question": "Which statement handles exceptions?", "options": ["try/except","try/catch","begin/rescue","handle"], "answer": "try/except"},
        ],
        "Data Types": [
            {"question": "Which type stores key:value pairs?", "options": ["list","tuple","dict","set"], "answer": "dict"},
            {"question": "Which type is unordered and unique collection?", "options": ["list","set","tuple","str"], "answer": "set"},
            {"question": "Which method returns keys of a dict d?", "options": ["d.keys()","keys(d)","d.getkeys()","getkeys(d)"], "answer": "d.keys()"},
            {"question": "Which type allows duplicate elements?", "options": ["set","dict","list","frozenset"], "answer": "list"},
            {"question": "Which of these is immutable?", "options": ["list","dict","tuple","set"], "answer": "tuple"},
            {"question": "Which literal creates bytes?", "options": ["b'abc'","'abc'","u'abc'","r'abc'"], "answer": "b'abc'"},
            {"question": "Which converts string to list of characters?", "options": ["list(s)","chars(s)","s.split()","splitchars(s)"], "answer": "list(s)"},
            {"question": "Which method merges a.extend(b)?", "options": ["a.concat(b)","a.extend(b)","a+b","append(b)"], "answer": "a.extend(b)"},
            {"question": "list.copy() makes what type of copy?", "options": ["deep","shallow","reference","no copy"], "answer": "shallow"},
            {"question": "Which type cannot be a dict key?", "options": ["tuple","int","list","str"], "answer": "list"},
            {"question": "What does range(5) produce?", "options": ["list","range","iterator","tuple"], "answer": "range"},
            {"question": "Which is mutable: dict or tuple?", "options": ["dict","tuple","both","none"], "answer": "dict"},
            {"question": "How to create empty set?", "options": ["{}","set()","[]","()"], "answer": "set()"},
            {"question": "Which returns (key,value) pairs from dict?", "options": ["d.items()","d.keys()","d.values()","d.pairs()"], "answer": "d.items()"},
            {"question": "Which converts to string?", "options": ["str()","to_str()","string()","format()"], "answer": "str()"},
            {"question": "Which is sequence type?", "options": ["set","dict","str","None"], "answer": "str"},
            {"question": "Which is mutable sequence?", "options": ["tuple","str","list","frozenset"], "answer": "list"},
            {"question": "Which method removes by value from list?", "options": ["remove()","pop()","del()","discard()"], "answer": "remove()"},
            {"question": "Which method returns index of item?", "options": ["index()","find()","locate()","search()"], "answer": "index()"},
            {"question": "Which literal creates raw string?", "options": ["r'abc'","'abc'","b'abc'","u'abc'"], "answer": "r'abc'"},
        ],
        "Control Flow": [
            {"question": "Which checks condition?", "options": ["for","if","while","switch"], "answer": "if"},
            {"question": "Which loop runs a fixed number of times?", "options": ["while","for","do-while","repeat"], "answer": "for"},
            {"question": "Which statement skips to next iteration?", "options": ["pass","continue","break","skip"], "answer": "continue"},
            {"question": "Which exits a loop?", "options": ["exit","break","return","stop"], "answer": "break"},
            {"question": "What does 'elif' mean?", "options": ["else if","else once","else loop","end if"], "answer": "else if"},
            {"question": "How to handle exceptions?", "options": ["try/except","try/catch","begin/rescue","except"], "answer": "try/except"},
            {"question": "Which runs while condition true?", "options": ["for","while","repeat","loop"], "answer": "while"},
            {"question": "Which comparison operator checks equality?", "options": ["=","==","is","equals()"], "answer": "=="},
            {"question": "Which checks identity?", "options": ["==","is","===","equals"], "answer": "is"},
            {"question": "Which statement returns from function?", "options": ["stop","break","return","exit"], "answer": "return"},
            {"question": "Which creates an anonymous function?", "options": ["lambda","def","anon","function"], "answer": "lambda"},
            {"question": "Which keyword makes generator yield?", "options": ["yield","return","generate","yieldfrom"], "answer": "yield"},
            {"question": "What does 'pass' do?", "options": ["placeholder","break","continue","return"], "answer": "placeholder"},
            {"question": "Which checks multiple conditions (AND)?", "options": ["&&","AND","and","&"], "answer": "and"},
            {"question": "Which loop can have else clause?", "options": ["for only","while only","for and while","none"], "answer": "for and while"},
            {"question": "Which statement raises exception?", "options": ["raise","throw","error","abort"], "answer": "raise"},
            {"question": "Which keyword used in conditional expression 'x if cond else y'?", "options": ["if","cond","else","then"], "answer": "if"},
            {"question": "What happens if exception not handled?", "options": ["Program continues","Traceback and stops","Ignored","Default handles"], "answer": "Traceback and stops"},
            {"question": "Which is used to create loops?","options":["for","switch","case","goto"], "answer":"for"},
            {"question": "Which is correct multi-branch?","options":["if...elif...else","if...else...elif","switch...case","case...switch"], "answer":"if...elif...else"},
        ],
        "Functions": [
            {"question": "Which keyword defines a function?", "options": ["def","function","func","lambda"], "answer": "def"},
            {"question": "How to return a value from function?", "options": ["return","yield","break","exit"], "answer": "return"},
            {"question": "What is docstring?", "options": ["string in function","comment","annotation","none"], "answer": "string in function"},
            {"question": "How to pass arbitrary positional args?", "options": ["*args","**kwargs","args[]","varargs"], "answer": "*args"},
            {"question": "How to pass arbitrary keyword args?", "options": ["**kwargs","*args","kwargs[]","varkwargs"], "answer": "**kwargs"},
            {"question": "Which decorator preserves metadata when wrapping?", "options": ["functools.wraps","wraps()","decorator","preserve"], "answer": "functools.wraps"},
            {"question": "Which builtin gives list of attributes?", "options": ["dir()","attrs()","vars()","help()"], "answer": "dir()"},
            {"question": "Which is generator function?", "options": ["uses yield","uses return","uses generator()", "none"], "answer": "uses yield"},
            {"question": "Can functions be assigned to variables?", "options": ["Yes","No","Only lambdas","Only methods"], "answer": "Yes"},
            {"question": "What is recursion?", "options": ["function calling itself","loop","lambda","decorator"], "answer": "function calling itself"},
            {"question": "Which keyword gives closure access to outer non-global var?", "options": ["nonlocal","global","outer","closure"], "answer": "nonlocal"},
            {"question": "Which makes function static in class?", "options": ["@staticmethod","@classmethod","static","class"], "answer": "@staticmethod"},
            {"question": "Which makes function receive class as first arg?", "options": ["@classmethod","@staticmethod","@decorator","@class"], "answer": "@classmethod"},
            {"question": "Which built-in returns function doc?", "options": [".__doc__","help()","doc()","info()"], "answer": ".__doc__"},
            {"question": "Which statement ends function early?", "options": ["return","break","exit","stop"], "answer": "return"},
            {"question": "Which indicates generator yield sequence?", "options": ["yield","return","sequence()","generate"], "answer": "yield"},
            {"question": "Which module inspects functions?","options":["inspect","functools","itertools","types"], "answer":"inspect"},
            {"question": "Which returns function name?","options":["__name__","name()","fnname()","getname()"], "answer":"__name__"},
            {"question": "Which creates lambda that returns x+1?","options":["lambda x: x+1","def x: return x+1","lambda(x) => x+1","func x: x+1"], "answer":"lambda x: x+1"},
            {"question": "Which builtin caches functions results?","options":["functools.lru_cache","cache()","memoize()","store()"], "answer":"functools.lru_cache"},
        ],
        "Libraries": [
            {"question": "Which library is used for arrays?", "options": ["numpy","pandas","tkinter","requests"], "answer": "numpy"},
            {"question": "Which library is for dataframes?", "options": ["pandas","numpy","csv","json"], "answer": "pandas"},
            {"question": "Which library plots graphs?", "options": ["matplotlib","seaborn","both","none"], "answer": "both"},
            {"question": "Which is HTTP client library?", "options": ["requests","urllib3","http","All"], "answer": "requests"},
            {"question": "Which built-in handles JSON?", "options": ["json","simplejson","ujson","rapidjson"], "answer": "json"},
            {"question": "Which is ML library?", "options": ["scikit-learn","mlpack","keras-only","tensorflow-only"], "answer": "scikit-learn"},
            {"question": "Which helps building web apps?", "options": ["flask","django","fastapi","All"], "answer": "All"},
            {"question": "Which is GUI toolkit built-in?", "options": ["tkinter","PyQt","wxPython","None"], "answer": "tkinter"},
            {"question": "Which package reads CSV easily?", "options": ["pandas.read_csv","csv.reader","numpy.loadtxt","All"], "answer": "pandas.read_csv"},
            {"question": "Which helps async programming?", "options": ["asyncio","threading","multiprocessing","socket"], "answer": "asyncio"},
            {"question": "Which library processes images?", "options": ["Pillow","OpenCV","both","skimage"], "answer": "both"},
            {"question": "Which is for web scraping?", "options": ["beautifulsoup4","requests","selenium","All"], "answer": "All"},
            {"question": "Which is for scientific computing beyond numpy?", "options": ["scipy","pandas","stats","ml"], "answer": "scipy"},
            {"question": "Which creates dashboards?", "options": ["dash","streamlit","panel","All"], "answer": "All"},
            {"question": "Which lib handles dates/times?", "options": ["datetime","time","arrow","All"], "answer": "All"},
            {"question": "Which manages packages?", "options": ["pip","conda","apt","npm"], "answer": "pip"},
            {"question": "Which shows high-level plotting API?", "options": ["seaborn","matplotlib","plotly","bokeh"], "answer": "seaborn"},
            {"question": "Which is for testing?", "options": ["pytest","unittest","nose","All"], "answer": "All"},
            {"question": "Which parses HTML?", "options": ["beautifulsoup4","lxml","html.parser","All"], "answer": "All"},
            {"question": "Which reduces boilerplate for functions?", "options": ["functools","itertools","contextlib","None"], "answer": "functools"},
        ],
    },
    "C": {
        "Basics": [
            {"question": "Which extension is for C source?", "options": [".c",".cpp",".java",".py"], "answer": ".c"},
            {"question": "Which function prints in C?", "options": ["printf()","cout<<","print()","System.out.println"], "answer": "printf()"},
            {"question": "Which header has printf?", "options": ["stdio.h","iostream","stdlib.h","string.h"], "answer": "stdio.h"},
            {"question": "Which marks end of statement?", "options": [";","\\n",".",":"], "answer": ";"},
            {"question": "What is entry point in C?", "options": ["main()","start()","init()","run()"], "answer": "main()"},
            {"question": "Which operator is address-of?", "options": ["&","*","%","$"], "answer": "&"},
            {"question": "Which operator dereferences pointer?", "options": ["*","&","->","."], "answer": "*"},
            {"question": "Which allocates memory in C?", "options": ["malloc()","new","alloc()","calloc()"], "answer": "malloc()"},
            {"question": "Which frees memory?", "options": ["free()","delete","dispose()","remove()"], "answer": "free()"},
            {"question": "Which qualifier for constants?", "options": ["const","static","volatile","register"], "answer": "const"},
            {"question": "Which is logical AND?", "options": ["&&","&","and","||"], "answer": "&&"},
            {"question": "Which header for dynamic memory?", "options": ["stdlib.h","stdio.h","string.h","math.h"], "answer": "stdlib.h"},
            {"question": "Which reads formatted input?", "options": ["scanf()","cin>>","read()","gets()"], "answer": "scanf()"},
            {"question": "Which returns size of type?", "options": ["sizeof","size","length","count"], "answer": "sizeof"},
            {"question": "Which type stores single char?", "options": ["char","string","int","byte"], "answer": "char"},
            {"question": "Which function converts string to int?", "options": ["atoi()","stoi()","parseInt()","strtoi()"], "answer": "atoi()"},
            {"question": "Which header for string functions?", "options": ["string.h","strings.h","cstring","str.h"], "answer": "string.h"},
            {"question": "Which storage class suggests fast access?", "options": ["register","auto","static","extern"], "answer": "register"},
            {"question": "Which is symbol for modulo operator?", "options": ["%","mod","/","//"], "answer": "%"},
            {"question": "Which produces compile-time macros?", "options": ["#define","macro()","define()","const"], "answer": "#define"},
        ],
        "Pointers": [
            {"question": "What stores memory address?", "options": ["pointer","variable","array","function"], "answer": "pointer"},
            {"question": "Which operator gives address-of variable?", "options": ["&","*","->","."], "answer": "&"},
            {"question": "Which operator dereferences pointer?", "options": ["*","&","->","."], "answer": "*"},
            {"question": "How to declare pointer to int?", "options": ["int *p;","int p*;","*int p;","pointer<int> p;"], "answer": "int *p;"},
            {"question": "Which allocates memory for pointer?", "options": ["malloc()","alloc()","new","create()"], "answer": "malloc()"},
            {"question": "Which frees memory pointed by pointer?", "options": ["free()","delete","dispose()","free_ptr()"], "answer": "free()"},
            {"question": "How to access member via pointer to struct?", "options": ["p->member","p.member","*p.member","p:member"], "answer": "p->member"},
            {"question": "Null pointer constant is?", "options": ["NULL","0","-1","none"], "answer": "NULL"},
            {"question": "Which is pointer to pointer declaration?", "options": ["int **pp;","int *p*;","int pp*;","pointer pointer;"], "answer": "int **pp;"},
            {"question": "Which converts void* to int* safely (C)?", "options": ["(int*)ptr","static_cast<int*>(ptr)","cast<int*>(ptr)","reinterpret"], "answer": "(int*)ptr"},
            {"question": "Which function copies memory blocks?", "options": ["memcpy()","strcpy()","copy()","memmove()"], "answer": "memcpy()"},
            {"question": "Which moves memory blocks safely for overlap?", "options": ["memmove()","memcpy()","move()","copy()"], "answer": "memmove()"},
            {"question": "Which returns pointer arithmetic unit in bytes?", "options": ["sizeof(type)","sizeof(ptr)","unit()","step()"], "answer": "sizeof(type)"},
            {"question": "Pointer arithmetic adds in units of?", "options": ["sizeof(pointed type)","1 byte","sizeof(void)","4 bytes"], "answer": "sizeof(pointed type)"},
            {"question": "Which declares function returning pointer to char?", "options": ["char* f();","char *f();","Both","None"], "answer": "Both"},
            {"question": "Which gets address of array element a[3]?", "options": ["&a[3]","a+3","*(a+3)","All"], "answer": "All"},
            {"question": "Pointer to function uses which syntax?", "options": ["int (*fptr)()","int fptr()","(*int f)()","funcptr<int>()"], "answer": "int (*fptr)()"},
            {"question": "Which common bug is pointer misuse leading to?", "options": ["segmentation fault","memory leak","infinite loop","type error"], "answer": "segmentation fault"},
            {"question": "Which term describes memory not freed?", "options": ["memory leak","dangling pointer","null pointer","overflow"], "answer": "memory leak"},
            {"question": "Which points to freed memory?", "options": ["dangling pointer","wild pointer","null pointer","double pointer"], "answer": "dangling pointer"},
        ],
        "Arrays": [
            {"question": "How to declare array of 10 ints?", "options": ["int a[10];","int a;","int[10] a;","array<int,10> a;"], "answer": "int a[10];"},
            {"question": "Which starts array index?", "options": ["0","1","-1","Depends"], "answer": "0"},
            {"question": "Which copies strings safe function?", "options": ["strncpy()","strcpy()","strcat()","sprintf()"], "answer": "strncpy()"},
            {"question": "Which gives number of elements in array a of size n?","options":["n","sizeof(a)/sizeof(a[0])","count(a)","len(a)"], "answer":"sizeof(a)/sizeof(a[0])"},
            {"question": "Which is 2D array declaration?", "options": ["int a[3][4];","int a[3,4];","int a3x4;","matrix<int> a;"], "answer": "int a[3][4];"},
            {"question": "Which is contiguous memory block?", "options": ["array","linked list","tree","map"], "answer": "array"},
            {"question": "Which can cause buffer overflow when misused?", "options": ["arrays","lists","maps","sets"], "answer": "arrays"},
            {"question": "Which header for mem functions used on arrays?", "options": ["string.h","stdio.h","stdlib.h","math.h"], "answer": "string.h"},
            {"question": "Which is correct to access element a[i]?", "options": ["a[i]","*(a+i)","Both","None"], "answer": "Both"},
            {"question": "Which sorts an array using qsort?", "options": ["qsort()","sort()","std::sort","qsort_s()"], "answer": "qsort()"},
            {"question": "Which function compares memory blocks?", "options": ["memcmp()","strcmp()","strncpy()","memcpy()"], "answer": "memcmp()"},
            {"question": "Which is dynamic array allocation?", "options": ["malloc()","int a[10]","new int[10]","alloc()"], "answer": "malloc()"},
            {"question": "Which returns pointer to first element of array a?", "options": ["a","&a[0]","(a)","both"], "answer": "both"},
            {"question": "Which loops iterate array indexes?", "options": ["for","while","foreach","repeat"], "answer": "for"},
            {"question": "Which operator gets last index of array length n?", "options": ["n-1","n","-1","last()"], "answer": "n-1"},
            {"question": "Which is used to read array from stdin using scanf?","options":["scanf(\"%d\", &a[i])","scanf(a[i])","read(a)","get(a)"], "answer":"scanf(\"%d\", &a[i])"},
            {"question": "Which is multi-dimensional array stored row-major in C?", "options": ["row-major","column-major","both","none"], "answer": "row-major"},
            {"question": "Which causes off-by-one bug?", "options": ["wrong loop bounds","pointer arithmetic","memory alloc","type mismatch"], "answer": "wrong loop bounds"},
            {"question": "Which is dynamic resizing alternative in C++ but not C?", "options": ["std::vector","malloc","realloc","calloc"], "answer": "std::vector"},
            {"question": "Which can be used to initialize array at declaration?", "options": ["int a[3]={1,2,3};","int a[]={};","int a;","init(a)"], "answer": "int a[3]={1,2,3};"},
        ],
        "Functions": [
            {"question": "Which declares function prototype?", "options": ["int f(int);","f(int) int;","declare f();","proto f();"], "answer": "int f(int);"},
            {"question": "Which returns value from function?", "options": ["return","yield","break","exit"], "answer": "return"},
            {"question": "Which specifies external linkage of function?", "options": ["extern","static","register","auto"], "answer": "extern"},
            {"question": "Which defines function with no params in C?", "options": ["void f(void)","void f()","f()","function f()"], "answer": "void f(void)"},
            {"question": "Which is recursion example?", "options": ["function calling itself","loop calling itself","macro","pointer"], "answer": "function calling itself"},
            {"question": "Which keyword may suggest inline expansion?", "options": ["inline","static","register","extern"], "answer": "inline"},
            {"question": "Which function pointer declaration is valid?", "options": ["int (*fptr)(int)","int *fptr(int)","int fptr*()","(*int f)()"], "answer": "int (*fptr)(int)"},
            {"question": "Which passes array to function decays to pointer?", "options": ["Yes","No","Sometimes","Depends"], "answer": "Yes"},
            {"question": "Which scope is local to function?","options":["automatic","global","static","register"], "answer":"automatic"},
            {"question": "Which stores persistent value across calls?", "options": ["static local variable","auto variable","register variable","extern var"], "answer": "static local variable"},
            {"question": "Which returns void pointer from function?", "options": ["void *f();","void f*();","*void f();","void f()"], "answer": "void *f();"},
            {"question": "Which statement inside function returns no value if declared void?", "options": ["return;","return 0;","exit","break"], "answer": "return;"},
            {"question": "Which declares variable in block scope?", "options": ["int x;","extern int x;","static int x;","register int x;"], "answer": "int x;"},
            {"question": "Which header is required for math functions in C?","options":["math.h","stdlib.h","stdio.h","string.h"], "answer":"math.h"},
            {"question": "Which indicates undefined behavior?","options":["depends on implementation","portable","safe","standard"], "answer":"depends on implementation"},
            {"question": "Which allows function overloading in C?","options":["Not supported","Yes","partially","with macros"], "answer":"Not supported"},
            {"question": "Which can be used to pass large struct cheaply?", "options": ["pointer to struct","copy struct","global struct","none"], "answer": "pointer to struct"},
            {"question": "Which is used to declare inline function in header safely?","options":["static inline","inline","extern inline","header inline"], "answer":"static inline"},
            {"question": "Which is recommended for API function prototypes?","options":["Provide prototypes in header","No prototypes","Inline prototypes","Macro prototypes"], "answer":"Provide prototypes in header"},
            {"question": "Which can detect stack corruption?","options":["stack canaries","ASLR","malloc","free"], "answer":"stack canaries"},
        ],
    },
    "C++": {
        "Basics": [
            {"question": "Which extension is for C++ source?", "options": [".cpp",".c",".java",".py"], "answer": ".cpp"},
            {"question": "Which stream outputs in C++?", "options": ["cout","printf","System.out","print"], "answer": "cout"},
            {"question": "Which header for iostream?", "options": ["iostream","stdio.h","iostream.h","conio.h"], "answer": "iostream"},
            {"question": "Which creates an object of class X named o?", "options": ["X o;","new X o;","X::o;","class X o;"], "answer": "X o;"},
            {"question": "Which is constructor function?", "options": ["same name as class","init()","__construct","new"], "answer": "same name as class"},
            {"question": "Which keyword is used for inheritance?", "options": ["public","extends","inherits","implements"], "answer": "public"},
            {"question": "Which provides polymorphism via virtual functions?", "options": ["virtual","override","static","inline"], "answer": "virtual"},
            {"question": "Which is used to allocate memory on heap?", "options": ["new","malloc","alloc","create"], "answer": "new"},
            {"question": "Which releases memory allocated by new?", "options": ["delete","free","dispose","remove"], "answer": "delete"},
            {"question": "Which allows overloading functions?", "options": ["Yes","No","Only templates","Only macros"], "answer": "Yes"},
            {"question": "Which uses templates for generic programming?", "options": ["template","generic","param","type"], "answer": "template"},
            {"question": "Which is STL container for dynamic array?", "options": ["vector","arraylist","listbox","mapbox"], "answer": "vector"},
            {"question": "Which operator inserts into stream?", "options": ["<<",">>",":",","], "answer": "<<"},
            {"question": "Which supports RAII idiom?", "options": ["C++","C","Java","Python"], "answer": "C++"},
            {"question": "Which is name mangling relevant to?", "options": ["C++","C","Java","Python"], "answer": "C++"},
            {"question": "Which cast checks at runtime?","options":["dynamic_cast","static_cast","reinterpret_cast","const_cast"], "answer":"dynamic_cast"},
            {"question": "Which header for string class?","options":["<string>","string.h","cstring","str.h"], "answer":"<string>"},
            {"question": "Which allows operator overloading?","options":["Yes","No","Only for pointers","Only for classes"], "answer":"Yes"},
            {"question": "Which keyword marks destructor?","options":["~ClassName","delete ClassName","destruct","destroy"], "answer":"~ClassName"},
            {"question": "Which introduces smart pointers in std?","options":["unique_ptr","auto_ptr","shared_ptr","All"], "answer":"All"},
        ],
        "OOP": [
            {"question": "Which is encapsulation concept?", "options": ["Hiding internal state","Inheritance","Polymorphism","Abstraction"], "answer": "Hiding internal state"},
            {"question": "Which is polymorphism?","options":["Many forms","Single form","None","Class only"], "answer":"Many forms"},
            {"question": "Which is inheritance?","options":["Deriving class from base","Function overload","Operator overload","Template"], "answer":"Deriving class from base"},
            {"question": "Which access specifier restricts access to class only?","options":["private","public","protected","internal"], "answer":"private"},
            {"question": "Which constructs supports runtime polymorphism?","options":["virtual functions","templates","overloads","macros"], "answer":"virtual functions"},
            {"question": "Which keyword forbids further overriding?", "options": ["final","sealed","override","abstract"], "answer": "final"},
            {"question": "Which is abstract class?","options":["Contains pure virtual function","Has no members","Cannot be declared","Only templates"], "answer":"Contains pure virtual function"},
            {"question": "Which makes member accessible to derived classes?", "options":["protected","private","public","friend"], "answer":"protected"},
            {"question": "Which provides friend access to class?","options":["friend","extern","static","inline"], "answer":"friend"},
            {"question": "Which allows multiple inheritance?","options":["C++","Java","C#","Python"], "answer":"C++"},
            {"question": "Which is diamond problem related to?", "options":["multiple inheritance","templates","virtual functions","friend"], "answer":"multiple inheritance"},
            {"question": "Which resolves diamond problem?","options":["virtual inheritance","static inheritance","multiple overrides","none"], "answer":"virtual inheritance"},
            {"question": "Which is constructor initializer list?", "options":[": member(val)","{ member=val }","init()","None"], "answer":": member(val)"},
            {"question": "Which creates object lifetime automatic?","options":["stack allocation","heap allocation","global allocation","static"], "answer":"stack allocation"},
            {"question": "Which is destructor called when object goes out of scope?","options":["Yes","No","Sometimes","Never"], "answer":"Yes"},
            {"question": "Which keyword permits friend function?","options":["friend","allow","permit","grant"], "answer":"friend"},
            {"question": "Which ensures proper cleanup of resources?","options":["RAII","GC","Manual free","None"], "answer":"RAII"},
            {"question": "Which supports interface-like behavior?","options":["pure virtual class","struct","enum","typedef"], "answer":"pure virtual class"},
            {"question": "Which allows operator overloading for classes?","options":["operator keyword","overload keyword","class operator","def operator"], "answer":"operator keyword"},
            {"question": "Which idiom avoids copying heavy resources?","options":["move semantics","copy semantics","pass by value","global"], "answer":"move semantics"},
        ],
        "Templates": [
            {"question": "Which keyword introduces template?", "options": ["template","generic","param","type"], "answer": "template"},
            {"question": "Which allows type-parameterized functions?", "options": ["function templates","class templates","both","none"], "answer": "both"},
            {"question": "Which syntax declares template for class?", "options": ["template<typename T> class X {}","template<class T> X {}","template T class X {}","None"], "answer":"template<typename T> class X {}"},
            {"question": "Which resolves at compile time?","options":["templates","virtual functions","runtime polymorphism","dynamic_cast"], "answer":"templates"},
            {"question": "Which is template specialization?","options":["Provide special impl for specific type","Override virtual","Overload function","None"], "answer":"Provide special impl for specific type"},
            {"question": "Which is variadic template notation?","options":["template<typename... Args>","template<Args...>","template... Args","var template"], "answer":"template<typename... Args>"},
            {"question": "Which is SFINAE related to?", "options": ["templates","virtual","overloads","macros"], "answer":"templates"},
            {"question": "Which library uses templates heavily?", "options": ["STL","C stdlib","math lib","io lib"], "answer":"STL"},
            {"question": "Which type of container is std::vector<T>?", "options": ["template class","non-template","macro","special"], "answer":"template class"},
            {"question": "Which instantiates template?","options":["compiler","runtime","linker","programmer"], "answer":"compiler"},
            {"question": "Which is disadvantage of templates?","options":["long compile times","runtime errors","no type safety","none"], "answer":"long compile times"},
            {"question": "Which allows generic lambdas in C++14+?","options":["auto param","template lambda","generic lambda","both"], "answer":"auto param"},
            {"question": "Which is explicit template instantiation?","options":["template class X<int>;","explicit X<int>();","instantiate X<int>();","None"], "answer":"template class X<int>;"},
            {"question": "Which enables zero-overhead abstraction?","options":["templates","virtual functions","macros","exceptions"], "answer":"templates"},
            {"question": "Which tests template-based code compile-time?","options":["static_assert","assert","runtime test","unit test"], "answer":"static_assert"},
            {"question": "Which allows policy-based design?","options":["templates","interfaces","inheritance","composition"], "answer":"templates"},
            {"question": "Which is reason to avoid templates?","options":["compilation bloat","efficiency","safety","none"], "answer":"compilation bloat"},
            {"question": "Which keyword restricts template type via concepts (C++20)?","options":["requires","concept","constraint","enable_if"], "answer":"requires"},
            {"question": "Which aids readable diagnostics for templates?","options":["concepts","macros","typedefs","using"], "answer":"concepts"},
            {"question": "Which allows function templates to be overloaded?","options":["Yes","No","Only if specialized","Only if inline"], "answer":"Yes"},
        ],
        "STL": [
            {"question": "Which container provides dynamic array with random access?", "options": ["vector","list","map","set"], "answer": "vector"},
            {"question": "Which is associative container mapping keys to values?", "options": ["map","vector","list","queue"], "answer": "map"},
            {"question": "Which gives ordered set of unique elements?", "options": ["set","unordered_set","multiset","list"], "answer": "set"},
            {"question": "Which sorts using std::sort?","options":["random access iterators","forward iterators","input iterators","output iterators"], "answer":"random access iterators"},
            {"question": "Which is sequence container for FIFO?", "options": ["queue","stack","deque","vector"], "answer":"queue"},
            {"question": "Which is container with efficient insertion/removal at both ends?", "options": ["deque","vector","list","set"], "answer":"deque"},
            {"question": "Which adaptor gives LIFO behavior?", "options": ["stack","queue","priority_queue","list"], "answer":"stack"},
            {"question": "Which function obtains size of container?","options":[".size()",".length()","size() function","len()"], "answer":".size()"},
            {"question": "Which returns iterator to beginning?", "options":["begin()","start()","first()","head()"], "answer":"begin()"},
            {"question": "Which gives associative container with hashed keys?", "options":["unordered_map","map","hashmap","mapbox"], "answer":"unordered_map"},
            {"question": "Which sorts container in-place?","options":["std::sort","std::stable_sort","std::partial_sort","std::qsort"], "answer":"std::sort"},
            {"question": "Which algorithm reverses a range?","options":["std::reverse","std::rotate","std::swap","std::flip"], "answer":"std::reverse"},
            {"question": "Which returns end iterator?","options":["end()","last()","finish()","none"], "answer":"end()"},
            {"question": "Which removes duplicates when container sorted?","options":["std::unique","std::distinct","std::unique_copy","std::erase"], "answer":"std::unique"},
            {"question": "Which allows priority queue top element retrieval?","options":["priority_queue","queue","stack","deque"], "answer":"priority_queue"},
            {"question": "Which adaptor adds ability to push/pop in O(1)?","options":["stack","vector","list","map"], "answer":"stack"},
            {"question": "Which is complexity of vector push_back amortized?","options":["O(1)","O(n)","O(log n)","O(n^2)"], "answer":"O(1)"},
            {"question": "Which returns whether container empty?","options":["empty()","size()==0","isEmpty()","none"], "answer":"empty()"},
            {"question": "Which uses iterators to traverse container?","options":["Yes","No","Sometimes","depends"], "answer":"Yes"},
            {"question": "Which is associative container allowing duplicate keys?","options":["multimap","map","unordered_map","set"], "answer":"multimap"},
        ],
    },
    "Java": {
        "Basics": [
            {"question": "Which extension for Java source files?", "options": [".java",".class",".jar",".py"], "answer": ".java"},
            {"question": "Which method is entry point in Java?", "options": ["main()","start()","init()","run()"], "answer": "main()"},
            {"question": "Which keyword creates new object?", "options": ["new","create","alloc","instance"], "answer": "new"},
            {"question": "Which prints to console?", "options": ["System.out.println","cout","printf","print"], "answer": "System.out.println"},
            {"question": "Which is parent of all classes?", "options": ["Object","Class","Root","Parent"], "answer": "Object"},
            {"question": "Which keyword for inheritance?", "options": ["extends","implements","inherits","uses"], "answer": "extends"},
            {"question": "Which compares string content?","options":["equals()","==","compare()","match()"], "answer":"equals()"},
            {"question": "Which type holds true/false?", "options": ["boolean","bool","Boolean","bit"], "answer": "boolean"},
            {"question": "Which package contains ArrayList?", "options": ["java.util","java.lang","java.io","java.net"], "answer": "java.util"},
            {"question": "Which prevents method overriding?", "options": ["final","static","private","abstract"], "answer": "final"},
            {"question": "Which exception must be declared or handled?", "options": ["checked exception","runtime exception","error","all"], "answer": "checked exception"},
            {"question": "Which supports lambda expressions introduced in Java 8?", "options": ["Functional interface","Runnable","Callable","Comparable"], "answer": "Functional interface"},
            {"question": "Which is automatic GC?", "options": ["Yes","No","Sometimes","Manual"], "answer": "Yes"},
            {"question": "Which creates thread using Runnable?","options":["new Thread(r).start()","start(r)","run(r)","Thread.start(r)"], "answer":"new Thread(r).start()"},
            {"question": "Which forbids inheritance of class?","options":["final","sealed","private","static"], "answer":"final"},
            {"question": "Which converts string to int?","options":["Integer.parseInt()","parseInt()","toInt()","strToInt()"], "answer":"Integer.parseInt()"},
            {"question": "Which formats dates/time?","options":["java.time","SimpleDateFormat","DateFormat","All"], "answer":"All"},
            {"question": "Which JVM languages exist?","options":["Java","Kotlin","Scala","All"], "answer":"All"},
            {"question": "Which declares package at top?","options":["package","import","module","using"], "answer":"package"},
            {"question": "Which is access specifier for package-private?", "options": ["no modifier","public","private","protected"], "answer": "no modifier"},
        ],
        "OOP": [
            {"question": "Which concept hides internal details of class?", "options": ["Encapsulation","Polymorphism","Inheritance","Abstraction"], "answer": "Encapsulation"},
            {"question": "Which one allows many forms of method?","options":["Polymorphism","Inheritance","Encapsulation","Abstraction"], "answer":"Polymorphism"},
            {"question": "Which keyword to implement interface?", "options": ["implements","extends","inherits","uses"], "answer":"implements"},
            {"question": "Which is abstract class?","options":["class with abstract methods","interface","enum","annotation"], "answer":"class with abstract methods"},
            {"question": "Which prevents overriding?","options":["final","static","private","native"], "answer":"final"},
            {"question": "Which supports method overloading?","options":["Yes","No","Only constructors","Only static methods"], "answer":"Yes"},
            {"question": "Which supports method overriding?","options":["Yes","No","Only final","Only static"], "answer":"Yes"},
            {"question": "Which is interface default method since Java 8?","options":["default method","abstract method","static method","none"], "answer":"default method"},
            {"question": "Which is keyword to call parent constructor?","options":["super","this","parent","base"], "answer":"super"},
            {"question": "Which is final class cannot be subclassed?","options":["Yes","No","Sometimes","Depends"], "answer":"Yes"},
            {"question": "Which hides internal state behind methods?","options":["Encapsulation","Abstraction","Inheritance","Polymorphism"], "answer":"Encapsulation"},
            {"question": "Which facilitates code reuse between classes?","options":["Inheritance","Abstraction","Interface","Encapsulation"], "answer":"Inheritance"},
            {"question": "Which allows multiple inheritance of type?","options":["interfaces","classes","both","none"], "answer":"interfaces"},
            {"question": "Which provides method signature without implementation?","options":["interface","abstract class","class","enum"], "answer":"interface"},
            {"question": "Which is instanceof checks?", "options": ["object type","value equality","reference equality","nullity"], "answer":"object type"},
            {"question": "Which is marker interface example?", "options":["Serializable","Comparable","Runnable","Callable"], "answer":"Serializable"},
            {"question": "Which enforces contract for implementing classes?","options":["interface","abstract class","enum","annotation"], "answer":"interface"},
            {"question": "Which default access level for members?","options":["package-private","public","private","protected"], "answer":"package-private"},
            {"question": "Which avoids tight coupling between classes?","options":["interfaces","concrete classes","static methods","globals"], "answer":"interfaces"},
            {"question": "Which design principle helps open/closed?","options":["OCP","SRP","LSP","ISP"], "answer":"OCP"},
        ],
        "Inheritance": [
            {"question": "Which keyword used for inheritance?", "options": ["extends","implements","inherits","uses"], "answer": "extends"},
            {"question": "Which type of inheritance Java supports?","options":["single, multilevel, hierarchical","multiple","hybrid","all"], "answer":"single, multilevel, hierarchical"},
            {"question": "Which prevents method overriding in subclass?","options":["final","static","private","abstract"], "answer":"final"},
            {"question": "Which calls parent class constructor?","options":["super()","this()","parent()","base()"], "answer":"super()"},
            {"question": "Which is multilevel inheritance example?","options":["A->B->C","A->B and A->C","A implements B","None"], "answer":"A->B->C"},
            {"question": "Which uses interface to achieve multiple inheritance of type?","options":["implements","extends","inherits","use"], "answer":"implements"},
            {"question": "Which keyword used to refer to current object?","options":["this","self","me","current"], "answer":"this"},
            {"question": "Which is diamond problem avoided in Java by?","options":["interfaces and default methods","multiple inheritance","virtual inheritance","none"], "answer":"interfaces and default methods"},
            {"question": "Which access specifier prevents subclass access?","options":["private","public","protected","default"], "answer":"private"},
            {"question": "Which is method resolution in inheritance order?","options":["closest in chain","farthest","alphabetical","none"], "answer":"closest in chain"},
            {"question": "Which allows subclass access to protected member?","options":["Yes","No","Only same package","Only same class"], "answer":"Yes"},
            {"question": "Which enforces contract across hierarchy?","options":["abstract methods","final methods","static methods","private methods"], "answer":"abstract methods"},
            {"question": "Which creates IS-A relationship?","options":["Inheritance","Composition","Aggregation","Association"], "answer":"Inheritance"},
            {"question": "Which method cannot be overridden?","options":["static methods","instance methods","abstract methods","default methods"], "answer":"static methods"},
            {"question": "Which ensures Liskov Substitution Principle?","options":["Proper overrides","Wrong overrides","No overrides","Private methods"], "answer":"Proper overrides"},
            {"question": "Which is keyword to prevent class extension?","options":["final","sealed","closed","none"], "answer":"final"},
            {"question": "Which is example of hierarchical inheritance?","options":["A->B and A->C","A->B->C","B->A","None"], "answer":"A->B and A->C"},
            {"question": "Which is runtime polymorphism achieved by?","options":["method overriding","method overloading","static binding","compile-time"], "answer":"method overriding"},
            {"question": "Which word describes class abstraction?","options":["abstract","final","sealed","static"], "answer":"abstract"},
            {"question": "Which is super class reference to subclass object allowed?","options":["Yes","No","Sometimes","Never"], "answer":"Yes"},
        ],
        "Collections": [
            {"question": "Which package contains collections framework?", "options": ["java.util","java.lang","java.io","java.net"], "answer": "java.util"},
            {"question": "Which List implementation is dynamic array?", "options": ["ArrayList","LinkedList","Vector","Stack"], "answer": "ArrayList"},
            {"question": "Which Map implementation keeps insertion order?", "options": ["LinkedHashMap","HashMap","TreeMap","Hashtable"], "answer": "LinkedHashMap"},
            {"question": "Which Set disallows duplicates and is unordered?", "options": ["HashSet","TreeSet","LinkedHashSet","ArrayList"], "answer": "HashSet"},
            {"question": "Which class is thread-safe variant of ArrayList historically?", "options": ["Vector","ArrayList","LinkedList","Stack"], "answer": "Vector"},
            {"question": "Which deque interface provides double-ended queue?", "options": ["Deque","Queue","List","Set"], "answer": "Deque"},
            {"question": "Which returns iterator over collection?","options":["iterator()","getIterator()","listIterator()","all"], "answer":"iterator()"},
            {"question": "Which sorts elements of List using comparator?","options":["Collections.sort(list, comp)","list.sort()","Collections.stableSort()","sort()"], "answer":"Collections.sort(list, comp)"},
            {"question": "Which class provides priority queue behavior?","options":["PriorityQueue","Queue","Deque","LinkedList"], "answer":"PriorityQueue"},
            {"question": "Which map implementation sorts keys?","options":["TreeMap","HashMap","LinkedHashMap","Hashtable"], "answer":"TreeMap"},
            {"question": "Which interface represents sequence of elements?","options":["List","Set","Map","Queue"], "answer":"List"},
            {"question": "Which avoids concurrency issues by CopyOnWrite?","options":["CopyOnWriteArrayList","ArrayList","Vector","LinkedList"], "answer":"CopyOnWriteArrayList"},
            {"question": "Which method adds element to collection?","options":["add()","push()","insert()","append()"], "answer":"add()"},
            {"question": "Which returns size of collection?","options":["size()","length()","count()","getSize()"], "answer":"size()"},
            {"question": "Which supports key->value with null keys allowed?","options":["HashMap","TreeMap","Hashtable","ConcurrentHashMap"], "answer":"HashMap"},
            {"question": "Which is synchronized map wrapper?","options":["Collections.synchronizedMap(map)","new SynchronizedMap()","map.synchronized()","none"], "answer":"Collections.synchronizedMap(map)"},
            {"question": "Which data structure uses LIFO?","options":["Stack","Queue","Deque","List"], "answer":"Stack"},
            {"question": "Which interface supports random access?","options":["RandomAccess","List","Set","Map"], "answer":"RandomAccess"},
            {"question": "Which supports bulk operations like removeIf?","options":["Collection","List","Set","Map"], "answer":"Collection"},
            {"question": "Which returns unmodifiable view of list?","options":["Collections.unmodifiableList(list)","list.readonly()","list.freeze()","none"], "answer":"Collections.unmodifiableList(list)"},
        ],
    },
}
